import React, { useState, useEffect } from "react";
import { ArrowLeft, CheckCircle, FileText, Plus, Trash2, AlertTriangle, Pencil } from "lucide-react";
import { useNavigate, useLocation } from "react-router-dom";
import DataTable from "../../components/DataTable";
import { api } from "../../api";
import "../../styles/forms.css";

export default function SalesOrders() {
  const navigate = useNavigate();
  const location = useLocation();
  const [salesOrders, setSalesOrders] = useState([]);
  const [contacts, setContacts] = useState([]);
  const [products, setProducts] = useState([]);
  const [analyticAccounts, setAnalyticAccounts] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [selectedOrder, setSelectedOrder] = useState(null);
  const [budgetWarning, setBudgetWarning] = useState(null);

  const [formData, setFormData] = useState({
    customerId: "",
    soDate: new Date().toISOString().split("T")[0],
    orderNumber: "", // Auto-generated by backend
    lines: [{ productId: "", analyticAccountId: "", quantity: 1, unitPrice: 0 }],
  });

  const loadData = async () => {
    setIsLoading(true);
    try {
      const [soData, cData, pData, aData] = await Promise.all([
        api.getSalesOrders(),
        api.getContacts(),
        api.getProducts(),
        api.getAnalyticAccounts(),
      ]);
      setSalesOrders(soData);
      setContacts(cData);
      setProducts(pData);
      setAnalyticAccounts(aData);
    } catch (err) {
      console.error("Failed to load sales orders data:", err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadData();
    const queryParams = new URLSearchParams(location.search);
    if (queryParams.get("new") === "true") {
      setIsFormOpen(true);
    }
  }, [location]);

  const calculateTotal = () =>
    formData.lines.reduce(
      (sum, l) => sum + (Number(l.quantity) * Number(l.unitPrice) || 0),
      0,
    );

  const handleAddLine = () => {
    setFormData((prev) => ({
      ...prev,
      lines: [...prev.lines, { productId: "", analyticAccountId: "", quantity: 1, unitPrice: 0 }],
    }));
  };

  const handleRemoveLine = (idx) => {
    if (formData.lines.length <= 1) return;
    setFormData((prev) => ({
      ...prev,
      lines: prev.lines.filter((_, i) => i !== idx),
    }));
  };

  const handleLineChange = (idx, field, value) => {
    setFormData((prev) => {
      const newLines = [...prev.lines];
      const updatedLine = { ...newLines[idx], [field]: value };
      if (field === "productId") {
        const prod = products.find((p) => p.id === value);
        if (prod) {
          updatedLine.unitPrice = prod.sales_price || 0;
        }
      }
      newLines[idx] = updatedLine;
      return { ...prev, lines: newLines };
    });
  };

  const handleSave = async () => {
    if (!formData.customerId) return alert("Customer is required");
    if (formData.lines.some((l) => !l.productId))
      return alert("Product is required for all line items");

    setIsSaving(true);
    try {
      const payload = {
        customer_id: formData.customerId,
        so_number: formData.orderNumber,
        so_date: formData.soDate,
        lines: formData.lines.map((l) => ({
          product_id: l.productId,
          analytic_account_id: l.analyticAccountId || null,
          qty: Number(l.quantity),
          unit_price: Number(l.unitPrice),
        })),
      };

      const created = await api.createSalesOrder(payload);
      setSelectedOrder(created);
      await loadData();
      alert("Sales Order created successfully");
    } catch (err) {
      alert(err.message || "Failed to save sales order");
    } finally {
      setIsSaving(false);
    }
  };

  const handleConfirm = async () => {
    if (!selectedOrder) return;
    setIsSaving(true);
    try {
      const updated = await api.confirmSalesOrder(selectedOrder.id);
      setSelectedOrder(updated);
      await loadData();
      alert("Sales Order confirmed!");
    } catch (err) {
      alert(err.message || "Failed to confirm sales order");
    } finally {
      setIsSaving(false);
    }
  };

  const handleCreateInvoice = async () => {
    if (!selectedOrder) return;
    setIsSaving(true);
    try {
      await api.createInvoiceFromSalesOrder(selectedOrder.id);
      await loadData();
      alert("Customer Invoice created from Sales Order!");
      navigate("/customer-invoices");
    } catch (err) {
      alert(err.message || "Failed to create invoice");
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!selectedOrder) return;
    if (selectedOrder.status !== "DRAFT") {
      alert("Only DRAFT sales orders can be deleted.");
      return;
    }
    if (!window.confirm("Are you sure you want to delete this sales order? This cannot be undone.")) return;

    setIsSaving(true);
    try {
      await api.deleteSalesOrder(selectedOrder.id);
      await loadData();
      alert("Sales Order deleted successfully");
      handleCloseForm();
    } catch (err) {
      alert(err.message || "Failed to delete");
    } finally {
      setIsSaving(false);
    }
  };

  const handleCloseForm = () => {
    setIsFormOpen(false);
    setSelectedOrder(null);
    setFormData({
      customerId: "",
      soDate: new Date().toISOString().split("T")[0],
      orderNumber: "",
      lines: [{ productId: "", analyticAccountId: "", quantity: 1, unitPrice: 0 }],
    });
  };

  const handleRowClick = async (row) => {
    setIsLoading(true);
    try {
      const fullDoc = await api.getSalesOrderById(row.id);
      setSelectedOrder(fullDoc);
      setFormData({
        customerId: fullDoc.customer_id || "",
        soDate: fullDoc.so_date ? new Date(fullDoc.so_date).toISOString().split("T")[0] : "",
        orderNumber: fullDoc.so_number || "",
        lines: fullDoc.lines?.map((l) => ({
          productId: l.product_id,
          analyticAccountId: l.analytic_account_id || "",
          quantity: l.qty || l.quantity || 1,
          unitPrice: l.unit_price || 0,
        })) || [{ productId: "", analyticAccountId: "", quantity: 1, unitPrice: 0 }],
      });
      setIsFormOpen(true);
    } catch (err) {
      console.error(err);
      alert("Failed to load details");
    } finally {
      setIsLoading(false);
    }
  };

  const handleDeleteRow = async (e, id, status) => {
    e.stopPropagation();
    if (status !== "DRAFT") {
      alert("Only DRAFT sales orders can be deleted.");
      return;
    }
    if (!window.confirm("Are you sure you want to delete this sales order?")) return;
    try {
      await api.deleteSalesOrder(id);
      await loadData();
    } catch (err) {
      alert(err.message || "Failed to delete");
    }
  };

  const columns = [
    { header: "SO No.", accessor: "so_number", render: (row) => <strong>{row.so_number}</strong> },
    { header: "Customer", render: (row) => row.contact?.name || "-" },
    { header: "SO Date", render: (row) => new Date(row.so_date).toLocaleDateString("en-IN") },
    { header: "Total", render: (row) => `₹ ${Number(row.total || 0).toLocaleString("en-IN")}` },
    {
      header: "Status",
      render: (row) => (
        <span className={`fv-badge ${row.status === "CONFIRMED" ? "fv-badge-confirmed" : "fv-badge-draft"}`}>
          {row.status}
        </span>
      ),
    },
    {
      header: "Action",
      render: (row) => (
        <div style={{ display: 'flex', gap: '8px' }}>
          <button
            onClick={(e) => { e.stopPropagation(); handleRowClick(row); }}
            style={{ background: 'none', border: 'none', color: 'var(--valora-primary)', cursor: 'pointer', padding: '4px' }}
            title="Edit / View"
          >
            <Pencil size={16} />
          </button>
          <button
            onClick={(e) => handleDeleteRow(e, row.id, row.status)}
            style={{ background: 'none', border: 'none', color: 'var(--valora-error)', cursor: 'pointer', padding: '4px' }}
            title="Delete"
          >
            <Trash2 size={16} />
          </button>
        </div>
      ),
    },
  ];

  if (isFormOpen) {
    const userStr = localStorage.getItem("valora_user");
    const user = userStr ? JSON.parse(userStr) : null;
    const isAccountant = user?.role?.toLowerCase() === "accountant";
    const isConfirmed = selectedOrder?.status === "CONFIRMED" || selectedOrder?.status === "INVOICED";
    const isReadOnly = isConfirmed || (isAccountant && Boolean(selectedOrder));
    const grandTotal = calculateTotal();

    return (
      <div className="page-content">
        <div className="fv-page">
          <div className="fv-topbar">
            <div className="fv-topbar-left">
              <button className="fv-btn fv-btn-back" onClick={handleCloseForm}>
                <ArrowLeft size={15} /> Back
              </button>
              <div>
                <h1 className="fv-topbar-title">
                  {selectedOrder ? selectedOrder.so_number : "New Sales Order"}
                </h1>
                <p className="fv-topbar-subtitle">
                  {selectedOrder ? `Customer: ${contacts.find(c => c.id === formData.customerId)?.name || "—"}` : "Fill in the details below"}
                </p>
              </div>
            </div>

            <div className="fv-topbar-actions">
              <div className="fv-status-bar">
                <span className={`fv-status-step ${!selectedOrder || selectedOrder.status === "DRAFT" ? "active" : "done"}`}>Draft</span>
                <span className={`fv-status-step ${isConfirmed ? "active" : ""}`}>Confirmed</span>
              </div>

              {!selectedOrder && (
                <button className="fv-btn fv-btn-save" onClick={handleSave} disabled={isSaving}>
                  {isSaving ? "Saving…" : "Save Order"}
                </button>
              )}
              {selectedOrder && selectedOrder.status === "DRAFT" && (
                <button className="fv-btn fv-btn-ghost print-hide" style={{ color: "#DC2626" }} onClick={handleDelete} disabled={isSaving} title="Delete">
                  <Trash2 size={15} /> Delete
                </button>
              )}
              {selectedOrder && !isConfirmed && (
                <button className="fv-btn fv-btn-confirm" onClick={handleConfirm} disabled={isSaving}>
                  <CheckCircle size={15} /> Confirm
                </button>
              )}
              {selectedOrder && isConfirmed && (
                <button className="fv-btn fv-btn-bill" onClick={handleCreateInvoice} disabled={isSaving}>
                  <FileText size={15} /> Create Invoice
                </button>
              )}
              <button className="fv-btn fv-btn-ghost" onClick={handleCloseForm}>Cancel</button>
            </div>
          </div>

          <div className="fv-card">
            <div className="fv-card-body">
              <p className="fv-section-label">Order Details</p>
              <div className="fv-grid fv-grid-3">
                <div className="fv-field">
                  <label className="fv-label">SO No.</label>
                  <input
                    className="fv-input fv-input-autogen"
                    value={formData.orderNumber}
                    disabled
                    placeholder="Auto-Generated"
                  />
                </div>
                <div className="fv-field">
                  <label className="fv-label">Customer Name <span className="fv-required">*</span></label>
                  <select
                    className="fv-select"
                    value={formData.customerId}
                    onChange={e => setFormData({ ...formData, customerId: e.target.value })}
                    disabled={isReadOnly}
                  >
                    <option value="">— Select Customer —</option>
                    {contacts.map(c => (
                      <option key={c.id} value={c.id}>
                        {c.name}
                        {c.type ? ` (${c.type === "BOTH" ? "Customer & Vendor" : c.type})` : ""}
                      </option>
                    ))}
                  </select>
                </div>
                <div className="fv-field">
                  <label className="fv-label">SO Date</label>
                  <input
                    className="fv-input"
                    type="date"
                    value={formData.soDate}
                    onChange={e => setFormData({ ...formData, soDate: e.target.value })}
                    disabled={isReadOnly}
                  />
                </div>
              </div>
            </div>

            <div className="fv-lines-section">
              <p className="fv-lines-title">Sales Order Lines</p>
              <div className="fv-table-wrap">
                <table className="fv-table">
                  <thead>
                    <tr>
                      <th style={{ width: 40 }}>Sr.</th>
                      <th>Product <span style={{ color: "#DC2626" }}>*</span></th>
                      <th>Budget Analytics</th>
                      <th style={{ textAlign: "right", width: 80 }}>Qty <span style={{ color: "#DC2626" }}>*</span></th>
                      <th style={{ textAlign: "right", width: 120 }}>Unit Price (₹) <span style={{ color: "#DC2626" }}>*</span></th>
                      <th style={{ textAlign: "right", width: 120 }}>Total (₹)</th>
                      {!isReadOnly && <th style={{ width: 40 }}></th>}
                    </tr>
                  </thead>
                  <tbody>
                    {formData.lines.map((line, idx) => {
                      const lineTotal = Number(line.quantity || 0) * Number(line.unitPrice || 0);
                      return (
                        <tr key={idx}>
                          <td style={{ textAlign: "center", fontWeight: 700, color: "#94A3B8", fontSize: "0.8rem" }}>{idx + 1}</td>
                          <td>
                            <select
                              className="fv-table-select"
                              value={line.productId}
                              onChange={e => handleLineChange(idx, "productId", e.target.value)}
                              disabled={isReadOnly}
                            >
                              <option value="">— Select Product —</option>
                              {products.map(p => (
                                <option key={p.id} value={p.id}>{p.name} (Sales: ₹{p.sales_price})</option>
                              ))}
                            </select>
                          </td>
                          <td>
                            <select
                              className="fv-table-select"
                              value={line.analyticAccountId}
                              onChange={e => handleLineChange(idx, "analyticAccountId", e.target.value)}
                              disabled={isReadOnly}
                            >
                              <option value="">— Select Analytics —</option>
                              {analyticAccounts.map(a => (
                                <option key={a.id} value={a.id}>{a.name}</option>
                              ))}
                            </select>
                          </td>
                          <td style={{ textAlign: "right" }}>
                            {isReadOnly ? (
                              <span style={{ fontWeight: 600 }}>{line.quantity}</span>
                            ) : (
                              <input
                                className="fv-table-input fv-table-input-sm"
                                type="number"
                                min="1"
                                value={line.quantity}
                                onChange={e => handleLineChange(idx, "quantity", e.target.value)}
                              />
                            )}
                          </td>
                          <td style={{ textAlign: "right" }}>
                            {isReadOnly ? (
                              <span style={{ fontWeight: 600 }}>₹ {Number(line.unitPrice).toLocaleString("en-IN")}</span>
                            ) : (
                              <input
                                className="fv-table-input fv-table-input-md"
                                type="number"
                                value={line.unitPrice}
                                onChange={e => handleLineChange(idx, "unitPrice", e.target.value)}
                              />
                            )}
                          </td>
                          <td style={{ textAlign: "right", fontWeight: 700, color: "#0F172A" }}>
                            ₹ {lineTotal.toLocaleString("en-IN")}
                          </td>
                          {!isReadOnly && (
                            <td>
                              <button className="fv-remove-btn" type="button" onClick={() => handleRemoveLine(idx)} title="Remove">✕</button>
                            </td>
                          )}
                        </tr>
                      );
                    })}
                  </tbody>
                  <tfoot>
                    <tr>
                      <td colSpan={!isReadOnly ? 5 : 5} style={{ textAlign: "right", color: "#64748B" }}>Grand Total</td>
                      <td style={{ textAlign: "right", color: "#714B67", fontSize: "1rem" }}>
                        ₹ {grandTotal.toLocaleString("en-IN")}
                      </td>
                      {!isReadOnly && <td />}
                    </tr>
                  </tfoot>
                </table>
              </div>
              {!isReadOnly && (
                <button className="fv-add-line" type="button" onClick={handleAddLine}>
                  <Plus size={14} /> Add Product Line
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="page-content" style={{ padding: 0 }}>
      <div className="page-header"><h1 className="page-title">Sales Orders</h1></div>
      {isLoading ? (
        <p style={{ padding: "40px", color: "#64748B" }}>Loading sales orders…</p>
      ) : (
        <DataTable
          title="Sales Order"
          columns={columns}
          data={salesOrders}
          onNewClick={() => { setSelectedOrder(null); setIsFormOpen(true); }}
          searchPlaceholder="Search sales orders…"
        />
      )}
    </div>
  );
}
