import React, { useState, useEffect } from "react";
import { Plus, Trash2, ArrowLeft, FileText, CheckCircle } from "lucide-react";
import { useNavigate, useLocation } from "react-router-dom";
import DataTable from "../../components/DataTable";
import { api } from "../../api";

export default function SalesOrders() {
  const navigate = useNavigate();
  const location = useLocation();
  const [salesOrders, setSalesOrders] = useState([]);
  const [contacts, setContacts] = useState([]);
  const [products, setProducts] = useState([]);
  const [analyticAccounts, setAnalyticAccounts] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [selectedOrder, setSelectedOrder] = useState(null);

  const [formData, setFormData] = useState({
    customerId: "",
    soDate: new Date().toISOString().split("T")[0],
    orderNumber: "", // Auto-generated by backend
    lines: [{ productId: "", analyticAccountId: "", quantity: 1, unitPrice: 0 }],
  });

  const loadData = async () => {
    setIsLoading(true);
    try {
      const [soData, cData, pData, aData] = await Promise.all([
        api.getSalesOrders(),
        api.getContacts(),
        api.getProducts(),
        api.getAnalyticAccounts(),
      ]);
      setSalesOrders(soData);
      setContacts(cData);
      setProducts(pData);
      setAnalyticAccounts(aData);
    } catch (err) {
      console.error("Failed to load sales orders data:", err);
    } finally {
      setIsLoading(false);
    }
  };
  // checkpoint 1
  useEffect(() => {
    loadData();
    const queryParams = new URLSearchParams(location.search);
    if (queryParams.get("new") === "true") {
      setIsFormOpen(true);
    }
  }, [location]);

  const handleAddLine = () => {
    setFormData((prev) => ({
      ...prev,
      lines: [...prev.lines, { productId: "", analyticAccountId: "", quantity: 1, unitPrice: 0 }],
    }));
  };

  const handleRemoveLine = (idx) => {
    if (formData.lines.length <= 1) return;
    setFormData((prev) => ({
      ...prev,
      lines: prev.lines.filter((_, i) => i !== idx),
    }));
  };

  const handleLineChange = (idx, field, value) => {
    setFormData((prev) => {
      const newLines = [...prev.lines];
      const updatedLine = { ...newLines[idx], [field]: value };
      if (field === "productId") {
        const prod = products.find((p) => p.id === value);
        if (prod) {
          updatedLine.unitPrice = prod.sales_price || 0;
        }
      }
      newLines[idx] = updatedLine;
      return { ...prev, lines: newLines };
    });
  };

  const calculateTotal = () => {
    return formData.lines.reduce(
      (sum, line) => sum + (Number(line.quantity) * Number(line.unitPrice) || 0),
      0,
    );
  };

  const handleSave = async () => {
    if (!formData.customerId) return alert("Customer is required");
    if (formData.lines.some((l) => !l.productId))
      return alert("Product is required for all line items");

    setIsSaving(true);
    try {
      const payload = {
        customer_id: formData.customerId,
        so_number: formData.orderNumber,
        so_date: formData.soDate,
        lines: formData.lines.map((l) => ({
          product_id: l.productId,
          analytic_account_id: l.analyticAccountId || null,
          qty: Number(l.quantity),
          unit_price: Number(l.unitPrice),
        })),
      };

      const created = await api.createSalesOrder(payload);
      setSelectedOrder(created);
      await loadData();
      alert("Sales Order created successfully");
    } catch (err) {
      alert(err.message || "Failed to save sales order");
    } finally {
      setIsSaving(false);
    }
  };

  const handleConfirm = async () => {
    if (!selectedOrder) return;
    setIsSaving(true);
    try {
      const updated = await api.confirmSalesOrder(selectedOrder.id);
      setSelectedOrder(updated);
      await loadData();
      alert("Sales Order confirmed!");
    } catch (err) {
      alert(err.message || "Failed to confirm sales order");
    } finally {
      setIsSaving(false);
    }
  };

  const handleCreateInvoice = async () => {
    if (!selectedOrder) return;
    setIsSaving(true);
    try {
      await api.createInvoiceFromSalesOrder(selectedOrder.id);
      await loadData();
      alert("Customer Invoice created from Sales Order!");
      navigate("/customer-invoices");
    } catch (err) {
      alert(err.message || "Failed to create invoice");
    } finally {
      setIsSaving(false);
    }
  };

  const handleCloseForm = () => {
    setIsFormOpen(false);
    setSelectedOrder(null);
    setFormData({
      customerId: "",
      soDate: new Date().toISOString().split("T")[0],
      orderNumber: "",
      lines: [{ productId: "", analyticAccountId: "", quantity: 1, unitPrice: 0 }],
    });
  };

  const handleRowClick = (row) => {
    setSelectedOrder(row);
    setFormData({
      customerId: row.customer_id || row.contact_id || "",
      soDate: row.so_date ? new Date(row.so_date).toISOString().split("T")[0] : "",
      orderNumber: row.so_number || "",
      lines: row.lines?.map((l) => ({
        productId: l.product_id,
        analyticAccountId: l.analytic_account_id || "",
        quantity: l.qty || l.quantity || 1,
        unitPrice: l.unit_price || 0,
      })) || [{ productId: "", analyticAccountId: "", quantity: 1, unitPrice: 0 }],
    });
    setIsFormOpen(true);
  };

  const columns = [
    { header: "SO No.", accessor: "so_number", render: (row) => <strong>{row.so_number}</strong> },
    { header: "Customer", render: (row) => row.contact?.name || "-" },
    { header: "SO Date", render: (row) => new Date(row.so_date).toLocaleDateString() },
    { header: "Total", render: (row) => `₹ ${Number(row.total || 0).toLocaleString()}` },
    {
      header: "Status",
      render: (row) => (
        <span
          style={{
            padding: "4px 10px",
            borderRadius: "6px",
            fontSize: "0.8rem",
            fontWeight: "700",
            backgroundColor: row.status === "CONFIRMED" ? "#D1FAE5" : "#FEF3C7",
            color: row.status === "CONFIRMED" ? "#059669" : "#D97706",
          }}
        >
          {row.status}
        </span>
      ),
    },
    {
      header: "Action",
      render: (row) => (
        <button
          className="secondary-btn"
          onClick={() => handleRowClick(row)}
          style={{ padding: "4px 10px", fontSize: "0.8rem" }}
        >
          View Form
        </button>
      ),
    },
  ];

  if (isFormOpen) {
    const userStr = localStorage.getItem("valora_user");
    const user = userStr ? JSON.parse(userStr) : null;
    const isAccountant = user?.role?.toLowerCase() === "accountant";

    const isConfirmed =
      selectedOrder?.status === "CONFIRMED" || selectedOrder?.status === "INVOICED";
    const isReadOnly = isConfirmed || (isAccountant && Boolean(selectedOrder));

    return (
      <div className="page-content" style={{ maxWidth: "1000px", margin: "0 auto" }}>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: "24px",
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
            <button
              className="secondary-btn"
              onClick={handleCloseForm}
              style={{ display: "flex", alignItems: "center", gap: "6px" }}
            >
              <ArrowLeft size={16} /> Back
            </button>
            <h2 style={{ margin: 0, fontSize: "1.5rem", fontWeight: "800" }}>
              Sales Order Form View
            </h2>
          </div>

          <div style={{ display: "flex", gap: "10px" }}>
            {!selectedOrder && (
              <button className="primary-btn" onClick={handleSave} disabled={isSaving}>
                Save Order
              </button>
            )}
            {selectedOrder && !isConfirmed && (
              <button
                className="primary-btn"
                onClick={handleConfirm}
                disabled={isSaving}
                style={{
                  backgroundColor: "#059669",
                  display: "flex",
                  alignItems: "center",
                  gap: "6px",
                }}
              >
                <CheckCircle size={16} /> Confirm
              </button>
            )}
            {selectedOrder && isConfirmed && (
              <button
                className="primary-btn"
                onClick={handleCreateInvoice}
                disabled={isSaving}
                style={{
                  backgroundColor: "#2563EB",
                  display: "flex",
                  alignItems: "center",
                  gap: "6px",
                }}
              >
                <FileText size={16} /> Create Invoice
              </button>
            )}
            <button className="secondary-btn" onClick={handleCloseForm}>
              Cancel
            </button>
          </div>
        </div>

        <div
          style={{
            background: "#FFFFFF",
            border: "2px solid #1E293B",
            borderRadius: "16px",
            padding: "24px",
          }}
        >
          <div
            className="form-row"
            style={{
              display: "grid",
              gridTemplateColumns: "1fr 1fr 1fr",
              gap: "20px",
              marginBottom: "24px",
            }}
          >
            <div className="form-field">
              <label style={{ fontWeight: "600", fontSize: "0.85rem" }}>SO No.</label>
              <input
                type="text"
                value={formData.orderNumber}
                onChange={(e) => setFormData({ ...formData, orderNumber: e.target.value })}
                disabled={true}
                placeholder="Auto-Generated"
              />
            </div>
            <div className="form-field">
              <label style={{ fontWeight: "600", fontSize: "0.85rem" }}>
                Customer Name (From Contact Master) *
              </label>
              <select
                value={formData.customerId}
                onChange={(e) => setFormData({ ...formData, customerId: e.target.value })}
                disabled={isReadOnly}
                required
              >
                <option value="">-- Select Customer --</option>
                {contacts.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.name}
                  </option>
                ))}
              </select>
            </div>
            <div className="form-field">
              <label style={{ fontWeight: "600", fontSize: "0.85rem" }}>SO Date</label>
              <input
                type="date"
                value={formData.soDate}
                onChange={(e) => setFormData({ ...formData, soDate: e.target.value })}
                disabled={isReadOnly}
              />
            </div>
          </div>

          <h3 style={{ fontSize: "1.1rem", fontWeight: "700", marginBottom: "16px" }}>
            Order Lines
          </h3>

          <table className="valora-table" style={{ width: "100%", marginBottom: "16px" }}>
            <thead>
              <tr>
                <th style={{ width: "50px" }}>Sr. No.</th>
                <th>Product (From Product Master)</th>
                <th>Budget Analytics</th>
                <th style={{ textAlign: "right" }}>Qty</th>
                <th style={{ textAlign: "right" }}>Unit Price (₹)</th>
                <th style={{ textAlign: "right" }}>Total (₹)</th>
                {!isReadOnly && <th style={{ width: "40px" }}></th>}
              </tr>
            </thead>
            <tbody>
              {formData.lines.map((line, idx) => {
                const lineTotal = Number(line.quantity || 0) * Number(line.unitPrice || 0);
                return (
                  <tr key={idx}>
                    <td>{idx + 1}</td>
                    <td>
                      <select
                        value={line.productId}
                        onChange={(e) => handleLineChange(idx, "productId", e.target.value)}
                        disabled={isReadOnly}
                        style={{
                          width: "100%",
                          padding: "6px",
                          borderRadius: "6px",
                          border: "1px solid #CBD5E1",
                        }}
                      >
                        <option value="">-- Select Product --</option>
                        {products.map((p) => (
                          <option key={p.id} value={p.id}>
                            {p.name} (₹ {p.sales_price})
                          </option>
                        ))}
                      </select>
                    </td>
                    <td>
                      <select
                        value={line.analyticAccountId}
                        onChange={(e) => handleLineChange(idx, "analyticAccountId", e.target.value)}
                        disabled={isReadOnly}
                        style={{
                          width: "100%",
                          padding: "6px",
                          borderRadius: "6px",
                          border: "1px solid #CBD5E1",
                        }}
                      >
                        <option value="">-- Select Analytics --</option>
                        {analyticAccounts.map((a) => (
                          <option key={a.id} value={a.id}>
                            {a.name}
                          </option>
                        ))}
                      </select>
                    </td>
                    <td style={{ textAlign: "right" }}>
                      <input
                        type="number"
                        min="1"
                        value={line.quantity}
                        onChange={(e) => handleLineChange(idx, "quantity", e.target.value)}
                        disabled={isReadOnly}
                        style={{
                          width: "70px",
                          textAlign: "right",
                          padding: "6px",
                          borderRadius: "6px",
                          border: "1px solid #CBD5E1",
                        }}
                      />
                    </td>
                    <td style={{ textAlign: "right" }}>
                      <input
                        type="number"
                        value={line.unitPrice}
                        onChange={(e) => handleLineChange(idx, "unitPrice", e.target.value)}
                        disabled={isReadOnly}
                        style={{
                          width: "100px",
                          textAlign: "right",
                          padding: "6px",
                          borderRadius: "6px",
                          border: "1px solid #CBD5E1",
                        }}
                      />
                    </td>
                    <td style={{ textAlign: "right", fontWeight: "700" }}>
                      ₹ {lineTotal.toLocaleString()}
                    </td>
                    {!isReadOnly && (
                      <td style={{ textAlign: "center" }}>
                        <button
                          type="button"
                          onClick={() => handleRemoveLine(idx)}
                          style={{
                            background: "none",
                            border: "none",
                            color: "#EF4444",
                            cursor: "pointer",
                          }}
                        >
                          <Trash2 size={16} />
                        </button>
                      </td>
                    )}
                  </tr>
                );
              })}
            </tbody>
            <tfoot>
              <tr style={{ fontWeight: "800", fontSize: "1.1rem", background: "#F8FAFC" }}>
                <td colSpan={5} style={{ textAlign: "right" }}>
                  Grand Total:
                </td>
                <td style={{ textAlign: "right", color: "#2563EB" }}>
                  ₹ {calculateTotal().toLocaleString()}
                </td>
                {!isReadOnly && <td></td>}
              </tr>
            </tfoot>
          </table>

          {!isReadOnly && (
            <button
              type="button"
              className="secondary-btn"
              onClick={handleAddLine}
              style={{ display: "inline-flex", alignItems: "center", gap: "6px" }}
            >
              <Plus size={16} /> Add Product Line
            </button>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="page-content" style={{ padding: 0 }}>
      <div className="page-header">
        <h1 className="page-title">Sales Orders</h1>
      </div>
      {isLoading ? (
        <p>Loading sales orders...</p>
      ) : (
        <DataTable
          title="Sales Order"
          columns={columns}
          data={salesOrders}
          onNewClick={() => {
            setSelectedOrder(null);
            setIsFormOpen(true);
          }}
          searchPlaceholder="Search sales orders..."
        />
      )}
    </div>
  );
}
